spring:

  profiles:
    active: local

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recordary?serverTimezone=UTC
    username: recordary-admin
    password: recordary

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false


server:
  error:
    whitelabel:
      enabled: false

  port: 8888
