spring:

  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

    h2:
      console:
        enabled: true

  session:
    store-type: jdbc

cloud:
  aws:
    s3:
      bucket: recordary-springboot-upload
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true



  thymeleaf:
    prefix: classpath:static/

  profiles:
    active: springdataJPA
