spring:

  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

    h2:
      console:
        enabled: true

  session:
    store-type: jdbc

  thymeleaf:
    prefix: classpath:static/
