spring:
  profiles:
    include: real

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true

  session:
    store-type: jdbc

  thymeleaf:
    prefix: classpath:static/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 128MB

server:
  error:
    include-exception: true
    whitelabel:
      enabled: false

cloud:
  aws:
    s3:
      bucket: recordary-springboot-upload

    region:
      static: ap-northeast-2

    stack:
      auto: false

    credentials:
      instanceProfile: true