spring:

  profiles:
    active: local

  mvc:
    throw-exception-if-no-handler-found: true

  thymeleaf:
    enabled: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recordary?serverTimezone=UTC
    username: recordary-admin
    password: recordary

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false

server:
  port: 8888