spring:

  jpa:
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

    h2:
      console:
        enabled: true

  session:
    store-type: jdbc